export class Emotion {
  constructor(name, score) {
     this.name = name;
     this.score = score;
  }
 }
 
 export const EmotionName = {
  Admiration: "Admiration",
  Adoration: "Adoration",
  AestheticAppreciation: "Aesthetic Appreciation",
  Amusement: "Amusement",
  Anger: "Anger",
  Anxiety: "Anxiety",
  Awe: "Awe",
  Awkwardness: "Awkwardness",
  Boredom: "Boredom",
  Calmness: "Calmness",
  Concentration: "Concentration",
  Confusion: "Confusion",
  Contemplation: "Contemplation",
  Contempt: "Contempt",
  Contentment: "Contentment",
  Craving: "Craving",
  Desire: "Desire",
  Determination: "Determination",
  Disappointment: "Disappointment",
  Disgust: "Disgust",
  Distress: "Distress",
  Doubt: "Doubt",
  Ecstasy: "Ecstasy",
  Embarrassment: "Embarrassment",
  EmpathicPain: "Empathic Pain",
  Entrancement: "Entrancement",
  Envy: "Envy",
  Excitement: "Excitement",
  Fear: "Fear",
  Guilt: "Guilt",
  Horror: "Horror",
  Interest: "Interest",
  Joy: "Joy",
  Love: "Love",
  Nostalgia: "Nostalgia",
  Pain: "Pain",
  Pride: "Pride",
  Realization: "Realization",
  Relief: "Relief",
  Romance: "Romance",
  Sadness: "Sadness",
  Satisfaction: "Satisfaction",
  Shame: "Shame",
  SurpriseNegative: "Surprise (negative)",
  SurprisePositive: "Surprise (positive)",
  Sympathy: "Sympathy",
  Tiredness: "Tiredness",
  Triumph: "Triumph",
 };